# Generated by Django 4.1 on 2024-03-06 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "用户信息",
                "verbose_name_plural": "用户信息",
            },
        ),
        migrations.CreateModel(
            name="SchemaConfig",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("schema", models.TextField()),
                ("name", models.CharField(max_length=255)),
                ("create_time", models.CharField(max_length=255)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicalStructureDataAdmin.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schema 配置表",
                "verbose_name_plural": "Schema 配置表",
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("medical_text", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "schema_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicalStructureDataAdmin.schemaconfig",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicalStructureDataAdmin.user",
                    ),
                ),
            ],
            options={
                "verbose_name": "转换记录信息",
                "verbose_name_plural": "转换记录信息",
            },
        ),
    ]
