# Generated by Django 4.1 on 2024-03-06 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("medicalStructureDataAdmin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="record",
            name="id",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="medical_text",
            field=models.TextField(verbose_name="医疗文本"),
        ),
        migrations.AlterField(
            model_name="record",
            name="schema_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="medicalStructureDataAdmin.schemaconfig",
                verbose_name="Schema ID",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="medicalStructureDataAdmin.user",
                verbose_name="用户ID",
            ),
        ),
        migrations.AlterField(
            model_name="schemaconfig",
            name="create_time",
            field=models.CharField(max_length=255, verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="schemaconfig",
            name="id",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="schemaconfig",
            name="name",
            field=models.CharField(max_length=255, verbose_name="名称"),
        ),
        migrations.AlterField(
            model_name="schemaconfig",
            name="schema",
            field=models.TextField(verbose_name="Schema"),
        ),
        migrations.AlterField(
            model_name="schemaconfig",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="medicalStructureDataAdmin.user",
                verbose_name="用户ID",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                max_length=255, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, verbose_name="密码"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, unique=True, verbose_name="用户名"),
        ),
    ]
