# Generated by Django 4.1 on 2024-03-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicalStructureDataAdmin",
            "0002_alter_record_create_time_alter_record_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="schemaconfig",
            name="create_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
        ),
    ]
