# Generated by Django 4.1 on 2024-03-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicalStructureDataAdmin", "0003_alter_schemaconfig_create_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLM",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "model_name",
                    models.IntegerField(
                        choices=[
                            (1, "ChatGPT4"),
                            (2, "文心一言4"),
                            (3, "MindSpore"),
                            (3, "华驼"),
                        ],
                        default=1,
                        verbose_name="模型名称",
                    ),
                ),
            ],
            options={
                "verbose_name": "模型表",
                "verbose_name_plural": "模型表",
            },
        ),
    ]
